DROP TABLE ORDERDETAILS;
DROP TABLE ORDERS;
DROP TABLE CUSTOMER;
DROP TABLE OFFICE;
DROP TABLE AGENT;
DROP TABLE BOOKING;

CREATE TABLE COUNTRY
(
  COUNTRYID VARCHAR2(5) NOT NULL,
  NAME VARCHAR2(40) NOT NULL,
  PRIMARY KEY(COUNTRYID)
);



INSERT INTO COUNTRY VALUES('C0001', 'Trinidad and Tobago');
INSERT INTO COUNTRY VALUES('C0002', 'United Kingdom');
INSERT INTO COUNTRY VALUES('C0003', 'United States');
INSERT INTO COUNTRY VALUES('C0004', 'Japan');
INSERT INTO COUNTRY VALUES('C0005', 'China');
INSERT INTO COUNTRY VALUES('C0006', 'France');
INSERT INTO COUNTRY VALUES('C0007', 'Egypt');
INSERT INTO COUNTRY VALUES('C0008', 'Germany');


